#Create a data frame that has Nichols' strain1 -  strain2 - PCC -Spearmen...(All meaningful distances)



#Quantitative:
##PCC
pcc= ( 1-abs(cor(t(All_Data_NAimputed))) ) %>% as.dist %>% melt_dist

##Spearman
spearman=( 1-abs(cor(t(All_Data_NAimputed),method="spearman")) ) %>% as.dist %>% melt_dist

#Note: Above pcc and spearman based distance are not real distance. It's just for my own convenience => real distance should be 1 - corr (no absolute value)


#Kendall (I am not sure about its application but it also cares about ranking like spearman does)
#Computing this takes much more time than other distances
##start.time=Sys.time()
##kendall=( 1-abs(cor(t(All_Data_NAimputed[1:500,]),method="kendall")) ) %>% as.dist %>% melt_dist
##end.time = Sys.time()
##end.time-start.time #Time difference of 1.61648 mins

##Euclidean
euclidean=get_dist(All_Data_NAimputed,method="euclidean") %>% melt_dist

##Mutual information
load("Data/mi_all.RData") #generated by mutual_info_quantitative.R
mi=(1-mi_all) %>% as.dist %>% melt_dist





#Qualitative:

##Euclidean
euclidean_qualitative=get_dist(Ternary_Data_324cutff_NAremoved,method="euclidean") %>% melt_dist
euclidean_collapsedCond=get_dist(Ternary_Data_324cutff_condCollapsed,method="euclidean") %>% melt_dist

##MHD3
mhd3=modified_hamming_distance_3(Ternary_Data_324cutff_NAremoved) %>% melt_dist
mhd3_collapsedCond=modified_hamming_distance_3(Ternary_Data_324cutff_condCollapsed) %>% melt_dist

##Mutual Information (Sho)
##Ref: https://cran.r-project.org/web/packages/infotheo/infotheo.pdf
###start.time = Sys.time()
###mi_ternary=( 1- mutinformation(t(Ternary_Data_324cutff_NAremoved) %>% as.data.frame) %>% natstobits ) %>% melt_dist 
###end.time = Sys.time()
###end.time-start.time #Time difference of 1.059961 hours
####save(mi_ternary,file="Data/mi_ternary.RData")
load("Data/mi_ternary.RData")

###start.time = Sys.time()
###mi_ternary_collapsedCond=( 1- mutinformation(t(Ternary_Data_324cutff_condCollapsed) %>% as.data.frame) %>% natstobits ) %>% melt_dist 
###end.time = Sys.time()
###end.time-start.time #Time difference of 22.47311 mins
#save(mi_ternary_collapsedCond,file="Data/mi_ternary_collapsedCond.RData")
load("Data/mi_ternary_collapsedCond.RData")


##GO similarity (Wang method)
str(strain1_strain2_WangBP_WangMF_WangCC)
###check if strain1-strain2 matches with those in "pcc" obj




#If the first 2 columns are the same across all distance dataframes here, I can simply use cbind()
identical(pcc[,1:2],spearman[,1:2])
identical(spearman[,1:2],euclidean[,1:2])
identical(euclidean[,1:2],mi[,1:2])
identical(euclidean[,1:2],euclidean_qualitative[,1:2])
identical(euclidean_qualitative[,1:2],euclidean_collapsedCond[,1:2])
identical(euclidean_collapsedCond[,1:2],mhd3[,1:2])
identical(mhd3[,1:2],mhd3_collapsedCond[,1:2])
identical(mhd3_collapsedCond[,1:2],mi_ternary[,1:2])
identical(mi_ternary[,1:2],mi_ternary_collapsedCond[,1:2])
###Just because the rownames are different, I have to check strain1 and strain2 separately for GO similarity obj
identical(strain1_strain2_WangBP_WangMF_WangCC$strain1,pcc[,1])
identical(strain1_strain2_WangBP_WangMF_WangCC$strain2,pcc[,2])


strain1strain2_allDistances=cbind(pcc,
                                  spearman=spearman$Distance,
                                  euclidean=euclidean$Distance,
                                  mi=mi$Distance,
                                  euclidean_qualitative=euclidean_qualitative$Distance,
                                  euclidean_collapsedCond=euclidean_collapsedCond$Distance,
                                  mhd3=mhd3$Distance,
                                  mhd3_collapsedCond=mhd3_collapsedCond$Distance,
                                  mi_ternary=mi_ternary$Distance,
                                  mi_ternary_collapsedCond=mi_ternary_collapsedCond$Distance,
                                  Wang_BP=strain1_strain2_WangBP_WangMF_WangCC$BP,
                                  Wang_MF=strain1_strain2_WangBP_WangMF_WangCC$MF,
                                  Wang_CC=strain1_strain2_WangBP_WangMF_WangCC$CC,
                                  stringsAsFactors=F)

colnames(strain1strain2_allDistances)[1:3]=c("strain1","strain2","pcc")

strain1strain2_allDistances$strain1=as.integer(strain1strain2_allDistances$strain1)
strain1strain2_allDistances$strain2=as.integer(strain1strain2_allDistances$strain2)

for(i in 3:dim(strain1strain2_allDistances)[2]){
  strain1strain2_allDistances[,i]=as.numeric(strain1strain2_allDistances[,i])
}

rownames(strain1strain2_allDistances)=as.character(1:7914231) #correct the rownames (don't know why it started with 2)


#save(strain1strain2_allDistances,file="Data/strain1strain2_allDistances.RData")








